language: ruby
rvm:
  - 2.2.3
services:
  - mongodb
before_script:
  - export LC_CTYPE=en_US.UTF-8
  - export LANG=en_US.UTF-8
  - export RACK_ENV=test
  - export MONGODB_URI=mongodb://localhost:27017/atom_test
script: bundle exec rspec spec
