version: '2'
services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/site

  site:
    extends: app
    command: bundle exec puma -p 80
    environment:
      - MONGODB_URI=mongodb://database:27017/atom_development
    links:
      - database


  builder:
    env_file: .env
    extends: app
    command: bundle exec rake site:build
    environment:
      - BUILD_URL=http://site
      - MONGODB_URI=mongodb://database:27017/atom_development
    links:
      - site
      - database

  test:
    extends: app
    command: rake spec
    environment:
      - RACK_ENV=test
      - MONGODB_URI=mongodb://database:27017/atom_test
    links:
      - database

  database:
    image: mongo:3.3
    ports:
      - "27017:27017"
