app:
  build: .
  ports:
    - "80:80"
  volumes:
    - .:/site

site:
  extends: app
  environment:
    - RETHINKDB_DB=atom_development
    - RETHINKDB_HOST=database
  links:
    - database

test:
  extends: app
  command: rake spec
  environment:
    - RACK_ENV=test
    - RETHINKDB_DB=atom_test
    - RETHINKDB_HOST=database
  links:
    - database

production:
  extends: app
  environment:
    - RETHINKDB_DB=atom
    - RETHINKDB_HOST=database
  links:
    - database

database:
  image: rethinkdb:latest
  ports:
    - "8080:8080"
