version: '2'
services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/site

  site:
    extends: app
    command: bundle exec foreman start
    environment:
      - DATABASE=atom_development
      - DATABASE_HOST=database
    links:
      - database


  builder:
    env_file: .env
    extends: app
    command: bundle exec rake site:build
    environment:
      - DATABASE=atom_development
      - DATABASE_HOST=database
    links:
      - site
      - database

  test:
    extends: app
    command: rake spec
    environment:
      - RACK_ENV=test
      - DATABASE=atom_test
      - DATABASE_HOST=database
    links:
      - database

  production:
    extends: app
    environment:
      - DATABASE=atom_packages
      - DATABASE_HOST=database
    links:
      - database

  database:
    image: mongo:3.3
    ports:
      - "27017:27017"
